### ISSUE TITLE
インフラ設計

### ISSUE THREAD

**Issue by yuma-matsui** [yuma-matsui/tasting_note#19]
構成図を書く

**Comment by yuma-matsui** [comment]
![Image](https://user-images.githubusercontent.com/70259961/203453064-975d5e2f-7827-4c8a-b6da-4ce092673df8.png)

**Comment by yoshitsugu** [comment]
- JSだけVercelで別ドメインだと、アクセス許可の設定などがやや大変かもしれません。(cross originになると思うので)
- VercelからRoute53への矢印は何をあらわしています？
- S3もALB経由とかにしないと、同じドメインにならないかなと思います。

**Comment by yuma-matsui** [comment]
ご確認いただきありがとうございます！
修正を行いましたのでご確認をお願いします。

## 修正点
- ホスティング先をS3に変更
- https通信を行うためにS3の前段にCloudFrontを設置（少々高いということでしたが一旦目を瞑ります）
- ALBの削除

## ご指摘いただいた点について

> JSだけVercelで別ドメインだと、アクセス許可の設定などがやや大変かもしれません。(cross originになると思うので)

考えが及んでいませんでした。
fjordメンターのyuuuさんの下記記事も参考にしましたが、

> [Rails 6\.1対応版: APIモードのRailsに対してCrossOriginなSPAからSession認証する方法 \- Qiita](https://qiita.com/Y_uuu/items/1651b181f06499c5cede)

今回は不用意に難しいことをするよりかはホスティング先をS3にして同一ドメインで進めようと思います。

***

> VercelからRoute53への矢印は何をあらわしています？

フロント(Vercel)からAPIを叩く際にVercel⇨Route53⇨ALB⇨Railsサーバーと思っていました..。
Vercel⇨ALB→Railsって感じでしょうか。

**Comment by yoshitsugu** [comment]
> Vercel⇨ALB→Railsって感じでしょうか。

Vercelは静的なファイル配信だけの想定でしたよね。
であればどちらかというと 

1. ブラウザ -> Vercel (JSなど取得)
2. ブラウザ(で動いているJS) -> ALB -> Rails

という形になるかなと思います。
Route53も名前解決だけなので、厳密にいうと

1. ブラウザ -名前解決の問い合わせ-> Route53
2. ブラウザ -解決されたIPでアクセス->CloudFront, ALBなど

という感じではあります。


- 認証だけFirebase Authenticationを使う感じでしょうか。
RailsからFirebase Authenticationへの矢印はないですが、Railsに直接アクセスしたら何でもアクセスできるようにならないように注意してくださいね。
この辺も簡単にやるならdevise gem使うとか、AWSに閉じるならcognito使うとか、いろいろ選択肢はありますね。

**Comment by yuma-matsui** [comment]
コメントありがとうございます！

通信の流れについてはいただいたコメントでおおよそ理解ができました。

Route53については取得したドメインとCloudFrontやALBのIPアドレスの紐付けを行うもので、
そのドメインに対してリクエストがあった際にIPアドレスを教えてあげますよということですね。

そしてALBは負荷分散のためにリクエストを捌くためのものであり、サーバーの前段に構えることで冗長化したサーバーにリクエストを振り分けるのが主な使われ方って感じでしょうか。

今回はサーバーを冗長化する予定がないのでALBについては取り除きます。

***

> 認証だけFirebase Authenticationを使う感じでしょうか。

RailsからFirebaseへの矢印が抜けておりましたので追加しました。

今回、[firebase-auth-rails](https://github.com/penguinwokrs/firebase-auth-rails)というgemを使用してバックエンドの認証管理を行う予定です。
こちらのgemでRedisが必要になるため、ECSタスク内でRedisのコンテナを用意しています。

**Comment by yoshitsugu** [comment]
> そしてALBは負荷分散のためにリクエストを捌くためのものであり、サーバーの前段に構えることで冗長化したサーバーにリクエストを振り分けるのが主な使われ方って感じでしょうか。

そうですね。あとはCloudFrontもそういう使い方ができますが、 `/api` 以下だけRails用のECSへ流す、みたいなルーティング処理をしたり、結構機能が豊富です。
ALB使わないでFargateって使えるんでしたっけ。一旦簡単に使うのであればECSのバックエンドをEC2インスタンス直接にしたほうがいいかもしれません。Fargateは実体マシンを意識しない作りになっているので、ALBなしで使えたかはちょっと僕も自信ないです。

**Comment by yuma-matsui** [comment]
@yoshitsugu 
コメントありがとうございます。
ご指摘いただいた通り、ALBなしではFargateが使えないようです。
2通り考えてみましたが、やはりご提案いただいたECSonEC2が無難でしょうか。

<details>
## ECS on EC2
![image](https://user-images.githubusercontent.com/70259961/199647116-f7f47235-0719-4900-8c43-904413aa93a8.png)

## ECS on Fargate(ALBの追加)
![image](https://user-images.githubusercontent.com/70259961/199647432-713b0801-8b4c-4d2e-b47f-1fff27c5ca46.png)

</details>

サーバーを冗長化しない場合はECSを使用するメリットってあまりない感じですかね...。
逆にいうとECSを使用する以上ALBを前段に構えて負荷分散をさせるのが基本であって、ALBなしでECSを使用することってほとんどないんでしょうか。

今回ECSを選択した理由としては下記2点ですが他の方法でも良かったかもです。

- 開発環境と本番環境の差異を無くしたい
- CDを手軽に行いたい

今回はこのまま進めようと思いますが、他の選択肢としてどういったものがあったのか調べてみようと思います。

**Comment by yoshitsugu** [comment]
> サーバーを冗長化しない場合はECSを使用するメリットってあまりない感じですかね...。

dockerでデプロイできるのはそれはそれで、あげられている2点のメリットではあると思います。

> 開発環境と本番環境の差異を無くしたい
> CDを手軽に行いたい


> 逆にいうとECSを使用する以上ALBを前段に構えて負荷分散をさせるのが基本であって、ALBなしでECSを使用することってほとんどないんでしょうか。

少なくとも今まで見てきたプロジェクトではだいたいALBは使っていましたね。
冗長化しないにしてもALBはおいていいかなと思います。
ECS on EC2 + ALBでも全然いいと思いますよ。

**Comment by yuma-matsui** [comment]
ありがとうございます！
調べてみたところFargateのコンテナへのログインもできるみたいなので今回は**ECS on Fargate**でいこうと思います。

**Comment by yoshitsugu** [comment]
では一旦OKとします！
