### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by yuma-matsui** [yuma-matsui/tasting_note#4]
ER図を書く

**Comment by yuma-matsui** [comment]
# ER図

![Image](https://user-images.githubusercontent.com/70259961/198563442-febdb798-0a52-4da2-9059-6bffea9f806f.png)


# テーブル設計

## User

| カラム名 | データ型 | 制約     | 説明       |
| -------- | -------- | -------- | ---------- |
| name     | string   | NOT NUll | ユーザー名 |
| uid      | string   | NOT NULL | Google認証 |

### Association
- has_many: tasting_sheets

## TastingSheet

| カラム名 | データ型 | 制約        | 説明                         |
| -------- | -------- | ----------- | ---------------------------- |
| name     | string   | NOT NULL    | テスト名                     |
| color    | string   | NOT NULL    | テイスティングするワインの色 |
| time     | string  | NOT NULL    | テスト実施時間(分)           |
| user_id  | integer  | FOREIGN KEY |                              |
| wine_id  | integer  | FOREIGN KEY, DEFAULT NULL |                              |

### Association
- belongs_to: user
- belongs_to: wine
- has_one:    appearance
- has_one:    flavor
- has_one:    taste
- has_one:    conclusion

## Appearance（外観）

| カラム名         | データ型 | 制約        | 説明   |
| ---------------- | -------- | ----------- | ------ |
| clarity          | string   | NOT NULL    | 清澄度 |
| brightness       | string   | NOT NULL    | 輝き   |
| intensity        | string   | NOT NULL    | 濃淡   |
| consistency      | string   | NOT NULL    | 粘性   |
| tasting_sheet_id | integer  | FOREIGN KEY |        |

### Association
- belongs_to: tasting_sheet
- has_many: appearance_colors
- has_many: appearance_impressions

## AppearanceColor
中間テーブル

| カラム名      | データ型 | 制約        | 説明 |
| ------------- | -------- | ----------- | ---- |
| appearance_id | integer  | FOREIGN KEY |      |
| color         | string   | NOT NULL    | 色調 |

### Association
- belongs_to: appearance

## AppearanceImpression
中間テーブル

| カラム名      | データ型 | 制約        | 説明                     |
| ------------- | -------- | ----------- | ------------------------ |
| appearance_id | integer  | FOREIGN KEY |                          |
| impression    | string   | NOT NULL    | 外観の印象               |

### Association
- belongs_to: appearance

## Flavor（香り）

| カラム名         | データ型 | 制約        | 説明                      |
| ---------------- | -------- | ----------- | ------------------------- |
| tasting_sheet_id | integer  | FOREIGN KEY |                           |

### Association
- belongs_to: tasting_sheet
- has_many: flavor_first_impressions
- has_many: flavor_fruits
- has_many: flavor_flowers
- has_many: flavor_spice
- has_many: flavor_impressions

## FlavorFirstImpression
中間テーブル

| カラム名         | データ型 | 制約        | 説明     |
| ---------------- | -------- | ----------- | -------- |
| flavor_id          | integer  | FOREIGN KEY |          |
| first_impression | string   | NOT NULL    | 第一印象 |

### Association
- belongs_to: flavor

## FlavorFruit
中間テーブル

| カラム名 | データ型 | 制約        | 説明 |
| -------- | -------- | ----------- | ---- |
| flavor_id  | integer  | FOREIGN KEY |      |
| fruit    | string   | NOT NULL    | 果実 |

### Association
- belongs_to: flavor

## FlavorFlower
中間テーブル

| カラム名     | データ型 | 制約        | 説明                                   |
| ------------ | -------- | ----------- | -------------------------------------- |
| flavor_id      | integer  | FOREIGN KEY |                                        |
| flower | string   | NOT NULL    | 花・植物・ハーブ・ナッツ・ドライ・菌類 |

### Association
- belongs_to: nose

## FlavorSpice
中間テーブル

| カラム名    | データ型 | 制約        | 説明                                           |
| ----------- | -------- | ----------- | ---------------------------------------------- |
| flavor_id     | integer  | FOREIGN KEY |                                                |
| spice | string   | NOT NULL    | 香辛料・芳香・化学物質・ミネラル・樽・動物・他 |

### Association
- belongs_to: flavor

## FlavorImpression
中間テーブル

| カラム名   | データ型 | 制約        | 説明                           |
| ---------- | -------- | ----------- | ------------------------------ |
| flavor_id    | integer  | FOREIGN KEY |                                |
| impression | string   | NOT NULL    | 香りの印象                     |

### Association
- belongs_to: flavor

## Taste（味わい）

| カラム名         | データ型 | 制約         | 説明                     |
| ---------------- | -------- | ------------ | ------------------------ |
| attack           | string   | NOT NULL     | アタック                 |
| sweetness        | string   | NOT NULL     | 甘み                     |
| acidity          | string   | NOT NULL     | 酸味                     |
| bitterness       | string   | DEFAULT NULL | 苦味, 白ワインの場合     |
| astringent       | string   | DEFAULT NULL | タンニン, 赤ワインの場合 |
| balance          | string   | NOT NULL     | バランス                 |
| alcohol          | string   | NOT NULL     | アルコール               |
| after_taste      | string   | NOT NULL     | 余韻                     |
| tasting_sheet_id | integer  | FOREIGN KEY  |                          |

### Association
- belongs_to: tasting_sheet

## Conclusion

| カラム名            | データ型 | 制約         | 説明                           |
| ------------------- | -------- | ------------ | ------------------------------ |
| evaluation          | string   | NOT NULL     | 評価                           |
| optimum_temperature | string   | NOT NULL     | 適正温度                       |
| glass               | string   | NOT NULL     | グラスの種類                   |
| decantage           | string   | DEFAULT NULL | デカンタージュ, 赤ワインの場合 |
| vintage             | integer  | NOT NULL     | 収穫年                         |
| country             | string   | NOT NULL     | 生産国                         |
| grape               | string   | NOT NULL     | ぶどう品種                     |
| tasting_sheet_id    | integer  | FOREIGN KEY  |                                |

### Association
- belongs_to: tasting_sheet

## Wine

| カラム名           | データ型 | 制約        | 説明                            |
| ------------------ | -------- | ----------- | ------------------------------- |
| name               | string   | NOT NULL    | ワイン名                        |
| vintage            | integer  | NOT NULL    | ヴィンテージ                    |
| country            | string   | NOT NULL    | 生産国                          |
| region             | string   |             | 生産地域                        |
| grape              | string   | NOT NULL    | ぶどう品種                      |
| alcohol_percentage | integer  | NOT NULL    | アルコール度数                  |
| memo               | string   |             | メモ                            |

### Association
- has_one: tasting_sheet

**Comment by yoshitsugu** [comment]
- Noseって鼻ですけどにおいだとflavourとかじゃないんですか？たぶん専門用語があると思うので、この辺の用語は英語のサイトでワインの分類しているものとか調べてみてはどうでしょうか。
- SecondAroma, ThirdAromaなどはAromaとして統合できないのか気になりました。
- Wineがtasting_sheet_idを持ってる形ですが、TastingSheetがwine_idを持つ形のほうが自然ではないのかな？と思いました。ワインは世界中のワイン一覧を理論的には作れますよね。(実現可能かはともかく)テイスティングシートはそのワインに対して、テイスティングというイベントが発生したら作られるものかと思いましたが、どうでしょうか。
- Conclusionが何をあらわすテーブルなのか、いまいちわかりませんでした。すいませんが説明してもらってもよいでしょうか。

**Comment by yuma-matsui** [comment]
@yoshitsugu 

ご確認いただきありがとうございます！

> Noseって鼻ですけどにおいだとflavourとかじゃないんですか？

いわゆるドメイン知識に含まれると思うので説明が少々長くなってしまいますがご容赦ください🙏
テイスティングコメント（テイスティングシート）は大きく4つで構成されております。
- 外観(Appearance)
- 香り(Nose)
- 味わい(Palate)
- 結論(Conclusion)

これらの英語表現については[WSET](https://en.wikipedia.org/wiki/Wine_%26_Spirit_Education_Trust)という英国の団体が行なっている認定試験のコメントシートを参考にしました。

![image](https://user-images.githubusercontent.com/70259961/197182198-25eeafa1-eb73-44cb-9c2e-42134677c935.png)

ご指摘の通り自分も香りはflavor、味わいはtasteの方がしっくりくるので、わかりやすさを重視して変更した方がやさそうですかね。

> Conclusionが何をあらわすテーブルなのか、いまいちわかりませんでした

この流れで**Conclusion**について説明しますが、「結論」のことでワインの総合評価になります。
葡萄品種や生産国といったワインの情報からワインの適切な飲み方など、そのワインに対する評価を表すテーブルです。

***

> SecondAroma, ThirdAromaなどはAromaとして統合できないのか気になりました。

> Wineがtasting_sheet_idを持ってる形ですが、TastingSheetがwine_idを持つ形のほうが自然ではないのかな？と思いました。

こちらについては文面で伝え切るのが難しいため、後日会話の際に説明いたします！

**Comment by yuma-matsui** [comment]
@yoshitsugu 
テーブル設計について修正を行いましたのでご確認をお願いします。

## 修正点
- TastingSheetにwine_idを持たせる構造にした
  - TastingSheetが作られたタイミングでwineは存在しないのでDEFAULT NULL制約
- 「香り」に関わるテーブル名を`Nose`から`Flavor`に変更した
- 「味わい」に関するテーブル名を`Palate`から`Taste`に変更した

## テーブル設計の元になった解答用紙
- 赤
![Image](https://user-images.githubusercontent.com/70259961/198568973-e243a20c-72ea-4dd0-85e9-c5999f90fcb4.png)

- 白
![Image](https://user-images.githubusercontent.com/70259961/198569076-7d153583-7e31-4221-a185-2bc156ac5411.png)

## 補足
- Appearance
  - AppearanceImpression
  - AppearanceColor
- Flavor
  - FlavorFirstImpression
  - FlavorFruit
  - FlavorFlower
  - FlavorSpice
  - FlavorImpression
- Taste
- Conclusion

上記テーブル群のカラムには答案用紙の選択肢がそれぞれ文字列で入ってくる想定です。
今回、フロントエンドとバックエンドを分けて開発する予定なので、フロント側に各答案選択肢のコレクションを用意して、コレクションに含まれる文字列のみ保存されるようにします。
バックエンド側でActiveHash等を使用して参照テーブルを用意することも考えましたが、選択肢に追加や変更があった際の変更コストを考え、文字列で保存することを選択しました。

## 答案の選択肢が変わった場合について
先日の会話にて、答案の選択肢が変わった場合にテーブルの再設計が必要になり、
その場合、現在の用にテーブル構造をがっちり固めていると変更が大変というご指摘があったかと思いますが、
下記理由から一旦この設計で進めようと思っています。

- ここ3年は答案用紙の変更がない
- 仮に変更があった場合でも1年に1回の変更となるため、TastingSheet2024のようにテーブル名の後方に年数をつけて管理する

***
以上、少し長くなりましたがご確認をお願いします。
